Repository cloudposse/terraform-aws-elasticache-memcached, pull requests merged in 2024-03, with the labels that each got.

#67 fix: sg arn output breaks when providing security groups IDs
  outputs.tf
Labels: bugfix, patch

#71 Update Scaffolding
  .github/mergify.yml
  README.md
  README.yaml
Labels: auto-update, no-release, do not merge, migration

#72 Add GitHub Settings
  .github/settings.yml
Labels: auto-update, no-release, do not merge, migration

#73 Add GitHub Settings
  .github/settings.yml
Labels: auto-update, no-release, migration, needs-cloudposse
